
export const ExtensionToMimeType = {
    html: "text/html",
    css: "text/css",
    xml: "text/xml",
    gif: "image/gif",
    jpeg: "image/jpeg",
    jpg: "image/jpeg",
    js: "application/x-javascript",
    txt: "text/plain",
    md: "text/markdown; charset=UTF-8",
    png: "image/png",
    tif: "image/tiff",
    tiff: "image/tiff",
    ico: "image/x-icon",
    jng: "image/x-jng",
    bmp: "image/x-ms-bmp",
    svg: "image/svg+xml",
    webp: "image/webp",
    pdf: "application/pdf",
    rtf: "application/rtf",
    '7z': "application/x-7z-compressed",
    zip: "application/zip",
    mid: "audio/midi",
    midi: "audio/midi",
    kar: "audio/midi",
    mp3: "audio/mpeg",
    ogg: "audio/ogg",
    ra: "audio/x-realaudio",
    mpeg: "video/mpeg",
    mpg: "video/mpeg",
    mov: "video/quicktime",
    mng: "video/x-mng",
    m4v: "video/mp4",
    mp4: "video/mp4",
};
